name: InterfaithNews.net
on:
  push:
    paths:
      - 'inn/**'
    branches:
      - main

jobs:
  publish-inn:
    name: Publish InterfaithNews.Net
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: FTP to Host Staging
        uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "inn"
          remoteDir: "public_html/stage.safnet.com/inn"
          #options: "--delete --asci"
          forceSsl: true
